### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by sethladd** [atebitftw/zart#1]
It's the first package on pub :)

**Comment by atebitftw** [comment]
I haven't revised this code since M2 I think, it's been a while.  I'll revisit this one soon.

**Comment by atebitftw** [comment]
@sethladd It only took 5 years.  Never let it be said that I don't follow up on stuff. ;)

Dart 2.x Compatible:
https://pub.dev/packages/zart/versions/1.0.1
